### PR TITLE
194 investigate bundlr connection bug

### LINKED ISSUE #194: Investigate bundlr connection bug
For a user who is already connected to bundlr:

Step 2 shows "not connected to bundlr" and fails to retrieve the upload price
Navigating to step 3 shows Connected to bundlr
Navigating back to step 2 then shows the upload price

The issue seems intermittent and might be related to session storage

### PR DESCRIPTION
**Pull request by knoll3**
Rebased on #190.

### CODE REVIEW

File: src/features/embalm/index.tsx [hunk 1]
```diff
@@ -13,6 +14,7 @@ const hideMagicFormFiller = false;
 
 export function Embalm() {
   useLoadArchaeologists();
+  useBundlrSession();
```
Comment (knoll3) [inline src/features/embalm/index.tsx:17]: This is the only change needed to fixed the bundlr connection issue.

**Review by mobiustripper42 — APPROVED** [review]
