### PR TITLE
Fix rewrap button getting stuck on loading state

### LINKED ISSUE #307: Rewrap - Handle Reject Transaction
When rejecting a rewrap transaction, the button doesn't reset -- says "Rewrapping....", and I can't hit the "cancel" button. My guess is this would be same behavior if rewrap TX were to fail.

### PR DESCRIPTION
**Pull request by knoll3**
Fixes the rewrap button getting stuck in a loading state after rejecting the transaction.

### Stuck in loading state
image

### CODE REVIEW

File: src/hooks/embalmerFacet/useRewrapSarcophagus.ts [hunk 1]
```diff
@@ -14,24 +14,29 @@ export function useRewrapSarcophagus(sarcoId: string, resurrectionTime: Date | n
 
   const timeInSeconds = resurrectionTime ? Math.trunc(resurrectionTime.getTime() / 1000) : 0;
 
-  const { config } = usePrepareContractWrite({
+  const { config, isError } = usePrepareContractWrite({
```
Comment (DarksightKellar) [inline src/hooks/embalmerFacet/useRewrapSarcophagus.ts]: Something I recently realised - while `isError` from `usePrepareContractWrite` will be true if the transaction *will* fail, a completely different `isError` is returned from `useContractWrite` if the transaction *actually* fails. I believe this means, `usePrepareContractWrite` would not catch a "failure" where the user cancels the request.

Check out `useCleanSarcophagus` for how I ended up using and exposing both of these `isError`s.

File: src/hooks/embalmerFacet/useRewrapSarcophagus.ts [hunk 2]
```diff
@@ -14,24 +14,29 @@ export function useRewrapSarcophagus(sarcoId: string, resurrectionTime: Date | n
...
+    },
+  });
+
   function rewrap() {
     write?.();
     setIsRewrapping(true);
   }
 
-  const { isSuccess } = useWaitForTransaction({
+  const { isSuccess, isLoading } = useWaitForTransaction({
```
Comment (DarksightKellar) [inline src/hooks/embalmerFacet/useRewrapSarcophagus.ts]: Looks like it'd be better to use `useWaitForTransaction`'s `isLoading` more than any of the other hooks'. As I work on the file upload UX I think I'll go ahead and update our other contract hooks to follow this pattern

**Review by DarksightKellar — CHANGES_REQUESTED** [review]
Looks good. Caught a potential bug with `isError` - left a comment

**Review by DarksightKellar — APPROVED** [review]
