### PR TITLE
Bundlr Chunked Uploader

### LINKED ISSUE #267: Bundlr Chunked Uploader
https://docs.bundlr.network/docs/client/advanced_uploading

If user uploaded file is >=50MB, use "chunked" uploading from Bundlr. 

Do some tests on larger files to confirm it is working. If it doesn't work with  >100MB on testnet, try using mainnet Bundlr.

### PR DESCRIPTION
**Pull request by solidoracle**
### Overview

If user uploaded file is >=50MB, Bundlr uses "chunked" uploading.

Had to change the Buffer.from encoding to hex for the app not to crash.

Tested upload with file up to 150MB

### CODE REVIEW

File: src/features/embalm/stepContent/hooks/useCreateSarcophagus/useUploadDoubleEncryptedFile.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export function useUploadDoubleEncryptedFile() {
       // Step 1: Encrypt the inner layer
       const encryptedInnerLayer = await encrypt(
         recipientState.publicKey,
-        Buffer.from(JSON.stringify(payload))
+        Buffer.from(JSON.stringify(payload), 'hex')
```
Comment (DarksightKellar) [inline src/features/embalm/stepContent/hooks/useCreateSarcophagus/useUploadDoubleEncryptedFile.ts:23]: Will need to do e2e tests to verify the archaeologist service can decode the data with its current codebase.

File: src/lib/constants/index.ts [hunk 2]
```diff
@@ -1,5 +1,6 @@
 export const maxSarcophagusNameLength = 60;
 export const maxFileSize = 200 * 1000 * 1000;
+export const chunkedUploaderFileSize = 50 * 1000 * 1000;
```
Comment (DarksightKellar) [inline src/lib/constants/index.ts:3]: 1000 or 1024? I'm really not sure
