### PR TITLE
Load failures from arch stats

### LINKED ISSUE #240: Fails + Unwraps on Select Archaeologist
Add unwraps and fail values to their respective columns on "Select Archaeologists".

Unwraps = all successful unwraps for an arch
Fails = all failed unwraps for an arch (grace period has passed with no keyshares)

### PR DESCRIPTION
**Pull request by knoll3**
Must be merged with https://github.com/sarcophagus-org/sarcophagus-v2-contracts/pull/103 from contracts. 

This adds failures to the arch metrics. Failures are calculated contract side (see contract PR for more details). 

This PR has not been thoroughly tested. Since the major changes to the contracts, my `generate-history` script broke so I haven't been able to generate a decent amount of data.

### CODE REVIEW

File: src/types/index.ts [hunk 1]
```diff
@@ -44,9 +44,10 @@ export interface ArchaeologistProfile {
   exists: boolean;
   minimumDiggingFee: BigNumber;
   maximumRewrapInterval: BigNumber;
-  successes: string[];
-  cleanups: string[];
-  accusals: string[];
+  successes: BigNumber;
+  cleanups: BigNumber;
+  accusals: BigNumber;
+  failures: BigNumber;
```
Comment (DarksightKellar) [inline src/types/index.ts:50]: Wondering - are cleanups going to be treated as failures? I'm a bit behind on the current metrics structure.

Comment (knoll3) [reply src/types/index.ts:50]: Yeah, cleanups are failures. The failure count here includes cleanups.

**Comment by DarksightKellar** [comment]
Failing build is because `0.7.0` isn't deployed yet. Will be merged in once deployed

**Review by sethhrbek — APPROVED** [review]
